services:
  backend:
    build: ./PYTHON
    container_name: backend
    restart: always
    env_file:
      - ./PYTHON/.env
    # Allows backend to see the standalone MySQL container
    extra_hosts:
      - "mysql_standalone:host-gateway"
    networks:
      - energy_net
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./REACT/dist:/usr/share/nginx/html/energymatrix/uat
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    networks:
      - energy_net

networks:
  energy_net:
    driver: bridge
