version: "3.9"

services:
  backend:
    build: ./PYTHON
    container_name: backend
    restart: always
    expose:
      - "8000"
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./REACT/dist:/usr/share/nginx/html/energymatrix/uat
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
