server {
    listen 80;
    server_name softcoretech.in;

    # FRONTEND (React)
    location /energymatrix/uat/ {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /energymatrix/uat/index.html;
    }

    # BACKEND API
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    # API under /energymatrix/uat
location /energymatrix/uat/api/ {
    proxy_pass http://backend:8000/api/;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
}
